# Generated by Django 4.2.19 on 2025-02-19 15:23

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auth_token_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=255, validators=[utils.validators.is_valid_password]),
        ),
    ]
